---
- name: centos8 - set repo zabbix
  dnf:
    pkg: "{{ zb_repo_centos8 }}"
    state: present
    disable_gpg_check: true

- name: centos8 - install agent2
  dnf:
    pkg={{ zb_agent2 }}

  notify: 
    - linux_copy_conf
    - linux_enable_agent

...
