---
- name: debian - set repo zabbix
  apt:
    deb: "{{ zb_repo_debian }}"

- name: debian - update cache
  apt:
    update_cache: yes

- name: debian - install agent2
  apt:
    pkg={{ zb_agent2 }}

  notify:
    - linux_copy_conf
    - linux_enable_agent

...
