---
# tasks file for zb-agent2
- import_tasks: debian_zb_agent.yml
  when: ansible_distribution == "Debian"

- import_tasks: centos_zb_agent.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora" or ansible_distribution == "RedHat"

- import_tasks: suse_zb_agent.yml
  when: ansible_distribution == "openSUSE Leap"

- import_tasks: ubuntu_zb_agent.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: windows_zb_agent.yml
  when: ansible_os_family == "Windows"

...
