---
- name: suse15 - set repo zabbix
  zypper:
    pkg: "{{ zb_repo_suse15 }}"
    state: present
    disable_gpg_check: true

- name: suse15 - install agent2
  zypper:
    pkg={{ zb_agent2 }}
    disable_gpg_check=true

  notify:
    - linux_copy_conf
    - linux_enable_agent

...
