---
# vars file for zb-agent2
zb_server: z-front.corp.intranet

zb_win_logfile: LogFile=c:\Zabbix\zabbix_agent2.log

# mantenha-se atualizado: https://www.zabbix.com/download (Agent 2)
zb_repo_centos: https://repo.zabbix.com/zabbix/6.2/rhel/9/x86_64/zabbix-release-6.2-3.el9.noarch.rpm

zb_repo_debian: https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bdebian11_all.deb

zb_repo_suse: https://repo.zabbix.com/zabbix/6.2/sles/15/x86_64/zabbix-release-6.2-2.sles15.noarch.rpm

zb_agent2:
  - zabbix-agent2
  - zabbix-agent2-plugin-*

...
